### ISSUE TITLE
Describe a Typical workflow for the frontend

### ISSUE THREAD

**Issue by thanpolas** [spikebrehm/nested-view#4]
What's the typical flow in the frontend's router file when a new page has been requested?

Is this valid?:

``` js
var data = {user: {name: 'Spike', email: 'spike@example.info'}};
var indexView = new IndexView(data);

// In the client, just call render.
var element = indexView.render().el;

$('#main').html( element );
```

More specifically:
1. On page load, do we re-render the template and re-inject it in the DOM while it's already there, served from the server?
   - if that's not the case, then what's the flow to make the app aware of the dom state? (bind events, etc).
2. When a new page is requested on the frontend, what happens to the old view? How is it properly Disposed / Garbage Collected ?

**Comment by spikebrehm** [comment]
Good question @thanpolas.  I left that complexity out of `nested-view`, and instead I'm developing it on Rendr, which should be released within the month (see blog post: http://nerds.airbnb.com/weve-launched-our-first-nodejs-app-to-product).
